<a href="https://colab.research.google.com/github/nickfiddler/FiddlerCodingPortfolio/blob/main/WeekToWeekNFL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This program is used as insights to sports gambling. I take tables off of teamrankings.com using beautiful soup, then use pandasql in order to gain information off of the table. As of now, I just have it searching for high ranked offenseses vs low ranked defenses, and offenses and defenses who have been hot (over 3 tds a game) and cold defenses (over 3 tds a game) in the last three games. I update this program week by week to help inform me of where to put anytime touchdown tds. This program showing on github was for Week 10 of the 2024 NFL Season

In [1]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.36)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26772 sha256=073c714499512f12ddad4c6f038d683831d8899c0fabff8390139bc02c73646d
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [2]:
#Importing packages
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [3]:
#Websites and creating the data frames
urlOffTds = 'https://www.teamrankings.com/nfl/stat/offensive-touchdowns-per-game'
dfOffTds = pd.DataFrame()
urlDefTds = 'https://www.teamrankings.com/nfl/stat/opponent-touchdowns-per-game'
dfDefTds = pd.DataFrame()
urlRushTds = 'https://www.teamrankings.com/nfl/stat/rushing-touchdowns-per-game'
dfRushTds = pd.DataFrame()
urlPassTds = 'https://www.teamrankings.com/nfl/stat/passing-touchdowns-per-game'
dfPassTds = pd.DataFrame()
urlDefRush = 'https://www.teamrankings.com/nfl/stat/opponent-rushing-touchdowns-per-game'
dfDefRush = pd.DataFrame()
urlDefPass = 'https://www.teamrankings.com/nfl/stat/opponent-passing-touchdowns-per-game'
dfDefPass = pd.DataFrame()

urlList = [urlOffTds,urlDefTds,urlRushTds,urlPassTds,urlDefRush,urlDefPass]
dfList = [dfOffTds,dfDefTds,dfRushTds,dfPassTds,dfDefRush,dfDefPass]
counter = 0

In [4]:
#this goes through the list I created from each websites and grabs the table from it
for url in urlList:
  page = requests.get(url)
  soup = BeautifulSoup(page.text,'html')

  table = soup.find_all('table')[0]
  th_list = table.find_all('th')
  titles = [title.text.strip() for title in th_list]

  df = pd.DataFrame(columns = titles)

  column_data = table.find_all('tr')
  for row in column_data[1:]:
    row_data = row.find_all('td')
    ind_row = [data.text.strip() for data in row_data]
    length = len(df)
    df.loc[length] = ind_row
  dfList[counter] = df.copy()
  counter = counter+1

In [5]:
#For some reason that I do not know, i had to set each table to the spot on
#its list to fill it
dfOffTds = dfList[0]
dfDefTds = dfList[1]
dfRushTds = dfList[2]
dfPassTds = dfList[3]
dfDefRush = dfList[4]
dfDefPass = dfList[5]

In [6]:
dfOffTds

   Rank           Team 2024 Last 3 Last 1 Home Away 2023
0     1      Baltimore  3.8    4.3    5.0  3.8  3.8  3.1
1     2        Detroit  3.7    3.7    3.0  4.0  3.4  3.4
2     3      Tampa Bay  3.2    2.7    2.0  3.0  3.5  2.2
3     3        Buffalo  3.2    3.0    2.0  4.3  2.5  3.1
4     3     Cincinnati  3.2    4.0    5.0  3.4  3.0  2.3
5     6   Philadelphia  3.1    4.0    4.0  2.7  3.3  2.6
6     7     Washington  2.9    2.3    3.0  2.2  3.6  2.2
7     8      Green Bay  2.7    2.3    1.0  2.6  2.8  2.6
8     9    Kansas City  2.6    2.7    1.0  2.4  2.8  2.2
9    10        Atlanta  2.5    3.3    2.0  2.2  3.0  1.8
10   11        Seattle  2.4    2.3    3.0  2.2  3.0  2.0
11   12        Arizona  2.4    3.3    4.0  2.7  2.0  2.1
12   12    New Orleans  2.4    1.3    2.0  2.2  2.6  2.4
13   14  San Francisco  2.3    2.3    2.0  2.0  2.8  3.5
14   14      Minnesota  2.3    1.7    0.0  2.8  2.0  2.2
15   16     Pittsburgh  2.2    3.0    4.0  2.3  2.2  1.7
16   17        Houston  2.2    1.7    2.0  2.0  2.4  2.2
17   17   Indianapolis  2.2    1.3    2.0  2.6  1.8  2.2
18   19        LA Rams  2.1    2.7    2.0  2.8  1.5  2.6
19   20    LA Chargers  2.1    3.3    3.0  2.3  2.0  2.1
20   21   Jacksonville  2.1    2.0    1.0  2.3  2.0  2.3
21   21        NY Jets  2.1    2.0    0.0  2.0  2.2  1.1
22   23        Chicago  2.0    0.7    0.0  2.0  2.0  2.1
23   24       Carolina  1.9    2.3    2.0  2.0  1.8  1.2
24   25      Tennessee  1.9    2.0    2.0  2.0  1.8  1.8
25   26         Denver  1.8    2.3    2.0  2.3  1.5  2.1
26   27      Las Vegas  1.8    1.3    2.0  2.3  1.4  1.8
27   28         Dallas  1.7    1.7    0.0  1.0  2.2  3.0
28   29    New England  1.6    2.0    1.0  2.3  1.2  1.5
29   30          Miami  1.5    2.3    3.0  1.8  1.3  3.2
30   30      NY Giants  1.5    2.0    2.0  0.8  2.2  1.5
31   32      Cleveland  1.4    2.0    1.0  2.0  0.8  2.3

In [7]:
#Workign with some sql
import pandasql as psql
x = "Philadelphia"
y = "Dallas"
query1 = f'SELECT * FROM dfOffTds WHERE Team = "{x}";'
result1 = psql.sqldf(query1,locals())
print("Offensive Tds")
print(f"{result1}")
query2 = f'SELECT * FROM dfDefTds WHERE Team = "{y}";'
result2 = psql.sqldf(query2,locals())
print("Tds Given Up")
print(f"{result2}")

Offensive Tds
  Rank          Team 2024 Last 3 Last 1 Home Away 2023
0    6  Philadelphia  3.1    4.0    4.0  2.7  3.3  2.6
Tds Given Up
  Rank    Team 2024 Last 3 Last 1 Home Away 2023
0   31  Dallas  3.3    3.7    4.0  4.8  2.2  2.4

In [8]:
#Checking to see if turning it into int works
print(int(result2['Rank'][0])+1)

32

In [10]:
#Away teams and home teams. It is important the same game is in the same position
ateams = ["Cincinnati","Pittsburgh","Philadelphia","NY Giants","Denver","Minnesota","Atlanta","San Francisco","Buffalo","New England","Tennessee","NY Jets","Detroit","Miami"]
hteams = ["Baltimore","Washington","Dallas","Carolina","Kansas City","Jacksonville","New Orleans","Tampa Bay","Indianapolis","Chicago","LA Chargers","Arizona","Houston","LA Rams"]

#Result Lists
goodOffense = []
badDeffense = []
last3Off = []
last3Def = []

#Looping through each game and checking for ranks and last 3 tds
for i in range(0,len(ateams)):
  offQuery = f'Select * FROM dfOffTds WHERE Team = "{ateams[i]}";'
  defQuery = f'Select * FROM dfDefTds WHERE Team = "{hteams[i]}";'
  offQuery2 = f'Select * FROM dfOffTds WHERE Team = "{hteams[i]}";'
  defQuery2 = f'Select * FROM dfDefTds WHERE Team = "{ateams[i]}";'

  offResult = psql.sqldf(offQuery,locals())
  defResult = psql.sqldf(defQuery,locals())
  offResult2 = psql.sqldf(offQuery2,locals())
  defResult2 = psql.sqldf(defQuery2,locals())

  offRank = int(offResult['Rank'][0])
  defRank = int(defResult['Rank'][0])
  offRank2 = int(offResult2['Rank'][0])
  defRank2 = int(defResult2['Rank'][0])

  awayOffLast3 = float(offResult['Last 3'][0])
  homeDefLast3 = float(defResult['Last 3'][0])
  homeOffLast3 = float(offResult2['Last 3'][0])
  awayDefLast3 = float(defResult2['Last 3'][0])

  if offRank <=8 and defRank>=24:
    goodOffense.append(ateams[i])
    badDeffense.append(hteams[i])

  if offRank2 <=8 and defRank2>=24:
    goodOffense.append(hteams[i])
    badDeffense.append(ateams[i])

  if awayOffLast3 >= 3.0 and homeDefLast3 >= 3.0:
    last3Off.append(ateams[i])
    last3Def.append(hteams[i])

  if homeOffLast3 >= 3.0 and awayDefLast3 >= 3.0:
    last3Off.append(hteams[i])
    last3Def.append(ateams[i])

#Printing the results
print(f"Good Offenses: {goodOffense}")
print(f"Bad Defenses: {badDeffense} \n")
print(f"Hot Offenses: {last3Off}")
print(f"Cold Deffenses: {last3Def}")

Good Offenses: ['Cincinnati', 'Baltimore', 'Philadelphia']
Bad Defenses: ['Baltimore', 'Cincinnati', 'Dallas']

Hot Offenses: ['Cincinnati', 'Baltimore', 'Pittsburgh', 'Philadelphia', 'LA Chargers']
Cold Deffenses: ['Baltimore', 'Cincinnati', 'Washington', 'Dallas', 'Tennessee']